//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.296
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OIT_Call_Manager {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Setting_general_autostart {
            get {
                return ((bool)(this["Setting_general_autostart"]));
            }
            set {
                this["Setting_general_autostart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Setting_general_showintray {
            get {
                return ((bool)(this["Setting_general_showintray"]));
            }
            set {
                this["Setting_general_showintray"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_понедельник_1пара_начало {
            get {
                return ((string)(this["Setting_понедельник_1пара_начало"]));
            }
            set {
                this["Setting_понедельник_1пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_понедельник_1пара_конец {
            get {
                return ((string)(this["Setting_понедельник_1пара_конец"]));
            }
            set {
                this["Setting_понедельник_1пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_понедельник_2пара_начало {
            get {
                return ((string)(this["Setting_понедельник_2пара_начало"]));
            }
            set {
                this["Setting_понедельник_2пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_понедельник_2пара_конец {
            get {
                return ((string)(this["Setting_понедельник_2пара_конец"]));
            }
            set {
                this["Setting_понедельник_2пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_понедельник_3пара_начало {
            get {
                return ((string)(this["Setting_понедельник_3пара_начало"]));
            }
            set {
                this["Setting_понедельник_3пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_понедельник_3пара_конец {
            get {
                return ((string)(this["Setting_понедельник_3пара_конец"]));
            }
            set {
                this["Setting_понедельник_3пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_понедельник_4пара_начало {
            get {
                return ((string)(this["Setting_понедельник_4пара_начало"]));
            }
            set {
                this["Setting_понедельник_4пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_понедельник_4пара_конец {
            get {
                return ((string)(this["Setting_понедельник_4пара_конец"]));
            }
            set {
                this["Setting_понедельник_4пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_понедельник_5пара_начало {
            get {
                return ((string)(this["Setting_понедельник_5пара_начало"]));
            }
            set {
                this["Setting_понедельник_5пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_понедельник_5пара_конец {
            get {
                return ((string)(this["Setting_понедельник_5пара_конец"]));
            }
            set {
                this["Setting_понедельник_5пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_понедельник_6пара_начало {
            get {
                return ((string)(this["Setting_понедельник_6пара_начало"]));
            }
            set {
                this["Setting_понедельник_6пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_понедельник_6пара_конец {
            get {
                return ((string)(this["Setting_понедельник_6пара_конец"]));
            }
            set {
                this["Setting_понедельник_6пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_вторник_1пара_начало {
            get {
                return ((string)(this["Setting_вторник_1пара_начало"]));
            }
            set {
                this["Setting_вторник_1пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_вторник_1пара_конец {
            get {
                return ((string)(this["Setting_вторник_1пара_конец"]));
            }
            set {
                this["Setting_вторник_1пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_вторник_2пара_начало {
            get {
                return ((string)(this["Setting_вторник_2пара_начало"]));
            }
            set {
                this["Setting_вторник_2пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_вторник_2пара_конец {
            get {
                return ((string)(this["Setting_вторник_2пара_конец"]));
            }
            set {
                this["Setting_вторник_2пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_вторник_3пара_начало {
            get {
                return ((string)(this["Setting_вторник_3пара_начало"]));
            }
            set {
                this["Setting_вторник_3пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_вторник_3пара_конец {
            get {
                return ((string)(this["Setting_вторник_3пара_конец"]));
            }
            set {
                this["Setting_вторник_3пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_вторник_4пара_начало {
            get {
                return ((string)(this["Setting_вторник_4пара_начало"]));
            }
            set {
                this["Setting_вторник_4пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_вторник_4пара_конец {
            get {
                return ((string)(this["Setting_вторник_4пара_конец"]));
            }
            set {
                this["Setting_вторник_4пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_вторник_5пара_начало {
            get {
                return ((string)(this["Setting_вторник_5пара_начало"]));
            }
            set {
                this["Setting_вторник_5пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_вторник_5пара_конец {
            get {
                return ((string)(this["Setting_вторник_5пара_конец"]));
            }
            set {
                this["Setting_вторник_5пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_вторник_6пара_начало {
            get {
                return ((string)(this["Setting_вторник_6пара_начало"]));
            }
            set {
                this["Setting_вторник_6пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_вторник_6пара_конец {
            get {
                return ((string)(this["Setting_вторник_6пара_конец"]));
            }
            set {
                this["Setting_вторник_6пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_среда_1пара_начало {
            get {
                return ((string)(this["Setting_среда_1пара_начало"]));
            }
            set {
                this["Setting_среда_1пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_среда_1пара_конец {
            get {
                return ((string)(this["Setting_среда_1пара_конец"]));
            }
            set {
                this["Setting_среда_1пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_среда_2пара_начало {
            get {
                return ((string)(this["Setting_среда_2пара_начало"]));
            }
            set {
                this["Setting_среда_2пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_среда_2пара_конец {
            get {
                return ((string)(this["Setting_среда_2пара_конец"]));
            }
            set {
                this["Setting_среда_2пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_среда_3пара_начало {
            get {
                return ((string)(this["Setting_среда_3пара_начало"]));
            }
            set {
                this["Setting_среда_3пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_среда_3пара_конец {
            get {
                return ((string)(this["Setting_среда_3пара_конец"]));
            }
            set {
                this["Setting_среда_3пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_среда_4пара_начало {
            get {
                return ((string)(this["Setting_среда_4пара_начало"]));
            }
            set {
                this["Setting_среда_4пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_среда_4пара_конец {
            get {
                return ((string)(this["Setting_среда_4пара_конец"]));
            }
            set {
                this["Setting_среда_4пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_среда_5пара_начало {
            get {
                return ((string)(this["Setting_среда_5пара_начало"]));
            }
            set {
                this["Setting_среда_5пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_среда_5пара_конец {
            get {
                return ((string)(this["Setting_среда_5пара_конец"]));
            }
            set {
                this["Setting_среда_5пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_среда_6пара_начало {
            get {
                return ((string)(this["Setting_среда_6пара_начало"]));
            }
            set {
                this["Setting_среда_6пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_среда_6пара_конец {
            get {
                return ((string)(this["Setting_среда_6пара_конец"]));
            }
            set {
                this["Setting_среда_6пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_четверг_1пара_начало {
            get {
                return ((string)(this["Setting_четверг_1пара_начало"]));
            }
            set {
                this["Setting_четверг_1пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_четверг_1пара_конец {
            get {
                return ((string)(this["Setting_четверг_1пара_конец"]));
            }
            set {
                this["Setting_четверг_1пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_четверг_2пара_начало {
            get {
                return ((string)(this["Setting_четверг_2пара_начало"]));
            }
            set {
                this["Setting_четверг_2пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_четверг_2пара_конец {
            get {
                return ((string)(this["Setting_четверг_2пара_конец"]));
            }
            set {
                this["Setting_четверг_2пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_четверг_3пара_начало {
            get {
                return ((string)(this["Setting_четверг_3пара_начало"]));
            }
            set {
                this["Setting_четверг_3пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_четверг_3пара_конец {
            get {
                return ((string)(this["Setting_четверг_3пара_конец"]));
            }
            set {
                this["Setting_четверг_3пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_четверг_4пара_начало {
            get {
                return ((string)(this["Setting_четверг_4пара_начало"]));
            }
            set {
                this["Setting_четверг_4пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_четверг_4пара_конец {
            get {
                return ((string)(this["Setting_четверг_4пара_конец"]));
            }
            set {
                this["Setting_четверг_4пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_четверг_5пара_начало {
            get {
                return ((string)(this["Setting_четверг_5пара_начало"]));
            }
            set {
                this["Setting_четверг_5пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_четверг_5пара_конец {
            get {
                return ((string)(this["Setting_четверг_5пара_конец"]));
            }
            set {
                this["Setting_четверг_5пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_четверг_6пара_начало {
            get {
                return ((string)(this["Setting_четверг_6пара_начало"]));
            }
            set {
                this["Setting_четверг_6пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_четверг_6пара_конец {
            get {
                return ((string)(this["Setting_четверг_6пара_конец"]));
            }
            set {
                this["Setting_четверг_6пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_пятница_1пара_начало {
            get {
                return ((string)(this["Setting_пятница_1пара_начало"]));
            }
            set {
                this["Setting_пятница_1пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_пятница_1пара_конец {
            get {
                return ((string)(this["Setting_пятница_1пара_конец"]));
            }
            set {
                this["Setting_пятница_1пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_пятница_2пара_начало {
            get {
                return ((string)(this["Setting_пятница_2пара_начало"]));
            }
            set {
                this["Setting_пятница_2пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_пятница_2пара_конец {
            get {
                return ((string)(this["Setting_пятница_2пара_конец"]));
            }
            set {
                this["Setting_пятница_2пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_пятница_3пара_начало {
            get {
                return ((string)(this["Setting_пятница_3пара_начало"]));
            }
            set {
                this["Setting_пятница_3пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_пятница_3пара_конец {
            get {
                return ((string)(this["Setting_пятница_3пара_конец"]));
            }
            set {
                this["Setting_пятница_3пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_пятница_4пара_начало {
            get {
                return ((string)(this["Setting_пятница_4пара_начало"]));
            }
            set {
                this["Setting_пятница_4пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_пятница_4пара_конец {
            get {
                return ((string)(this["Setting_пятница_4пара_конец"]));
            }
            set {
                this["Setting_пятница_4пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_пятница_5пара_начало {
            get {
                return ((string)(this["Setting_пятница_5пара_начало"]));
            }
            set {
                this["Setting_пятница_5пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_пятница_5пара_конец {
            get {
                return ((string)(this["Setting_пятница_5пара_конец"]));
            }
            set {
                this["Setting_пятница_5пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_пятница_6пара_начало {
            get {
                return ((string)(this["Setting_пятница_6пара_начало"]));
            }
            set {
                this["Setting_пятница_6пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_пятница_6пара_конец {
            get {
                return ((string)(this["Setting_пятница_6пара_конец"]));
            }
            set {
                this["Setting_пятница_6пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_суббота_1пара_начало {
            get {
                return ((string)(this["Setting_суббота_1пара_начало"]));
            }
            set {
                this["Setting_суббота_1пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_суббота_1пара_конец {
            get {
                return ((string)(this["Setting_суббота_1пара_конец"]));
            }
            set {
                this["Setting_суббота_1пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_суббота_2пара_начало {
            get {
                return ((string)(this["Setting_суббота_2пара_начало"]));
            }
            set {
                this["Setting_суббота_2пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_суббота_2пара_конец {
            get {
                return ((string)(this["Setting_суббота_2пара_конец"]));
            }
            set {
                this["Setting_суббота_2пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_суббота_3пара_начало {
            get {
                return ((string)(this["Setting_суббота_3пара_начало"]));
            }
            set {
                this["Setting_суббота_3пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_суббота_3пара_конец {
            get {
                return ((string)(this["Setting_суббота_3пара_конец"]));
            }
            set {
                this["Setting_суббота_3пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_суббота_4пара_начало {
            get {
                return ((string)(this["Setting_суббота_4пара_начало"]));
            }
            set {
                this["Setting_суббота_4пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_суббота_4пара_конец {
            get {
                return ((string)(this["Setting_суббота_4пара_конец"]));
            }
            set {
                this["Setting_суббота_4пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_суббота_5пара_начало {
            get {
                return ((string)(this["Setting_суббота_5пара_начало"]));
            }
            set {
                this["Setting_суббота_5пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_суббота_5пара_конец {
            get {
                return ((string)(this["Setting_суббота_5пара_конец"]));
            }
            set {
                this["Setting_суббота_5пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_суббота_6пара_начало {
            get {
                return ((string)(this["Setting_суббота_6пара_начало"]));
            }
            set {
                this["Setting_суббота_6пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_суббота_6пара_конец {
            get {
                return ((string)(this["Setting_суббота_6пара_конец"]));
            }
            set {
                this["Setting_суббота_6пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Setting_minimizeTrayOnStart {
            get {
                return ((bool)(this["Setting_minimizeTrayOnStart"]));
            }
            set {
                this["Setting_minimizeTrayOnStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBox_понедельник_1пара {
            get {
                return ((bool)(this["SettingCheckBox_понедельник_1пара"]));
            }
            set {
                this["SettingCheckBox_понедельник_1пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBox_понедельник_2пара {
            get {
                return ((bool)(this["SettingCheckBox_понедельник_2пара"]));
            }
            set {
                this["SettingCheckBox_понедельник_2пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBox_понедельник_3пара {
            get {
                return ((bool)(this["SettingCheckBox_понедельник_3пара"]));
            }
            set {
                this["SettingCheckBox_понедельник_3пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBox_понедельник_4пара {
            get {
                return ((bool)(this["SettingCheckBox_понедельник_4пара"]));
            }
            set {
                this["SettingCheckBox_понедельник_4пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBox_понедельник_5пара {
            get {
                return ((bool)(this["SettingCheckBox_понедельник_5пара"]));
            }
            set {
                this["SettingCheckBox_понедельник_5пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBox_понедельник_6пара {
            get {
                return ((bool)(this["SettingCheckBox_понедельник_6пара"]));
            }
            set {
                this["SettingCheckBox_понедельник_6пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBox_вторник_1пара {
            get {
                return ((bool)(this["SettingCheckBox_вторник_1пара"]));
            }
            set {
                this["SettingCheckBox_вторник_1пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBox_вторник_2пара {
            get {
                return ((bool)(this["SettingCheckBox_вторник_2пара"]));
            }
            set {
                this["SettingCheckBox_вторник_2пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBox_вторник_3пара {
            get {
                return ((bool)(this["SettingCheckBox_вторник_3пара"]));
            }
            set {
                this["SettingCheckBox_вторник_3пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBox_вторник_4пара {
            get {
                return ((bool)(this["SettingCheckBox_вторник_4пара"]));
            }
            set {
                this["SettingCheckBox_вторник_4пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBox_вторник_5пара {
            get {
                return ((bool)(this["SettingCheckBox_вторник_5пара"]));
            }
            set {
                this["SettingCheckBox_вторник_5пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBox_вторник_6пара {
            get {
                return ((bool)(this["SettingCheckBox_вторник_6пара"]));
            }
            set {
                this["SettingCheckBox_вторник_6пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBox_среда_1пара {
            get {
                return ((bool)(this["SettingCheckBox_среда_1пара"]));
            }
            set {
                this["SettingCheckBox_среда_1пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBox_среда_2пара {
            get {
                return ((bool)(this["SettingCheckBox_среда_2пара"]));
            }
            set {
                this["SettingCheckBox_среда_2пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBox_среда_3пара {
            get {
                return ((bool)(this["SettingCheckBox_среда_3пара"]));
            }
            set {
                this["SettingCheckBox_среда_3пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBox_среда_4пара {
            get {
                return ((bool)(this["SettingCheckBox_среда_4пара"]));
            }
            set {
                this["SettingCheckBox_среда_4пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBox_среда_5пара {
            get {
                return ((bool)(this["SettingCheckBox_среда_5пара"]));
            }
            set {
                this["SettingCheckBox_среда_5пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBox_среда_6пара {
            get {
                return ((bool)(this["SettingCheckBox_среда_6пара"]));
            }
            set {
                this["SettingCheckBox_среда_6пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBox_четверг_1пара {
            get {
                return ((bool)(this["SettingCheckBox_четверг_1пара"]));
            }
            set {
                this["SettingCheckBox_четверг_1пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBox_четверг_2пара {
            get {
                return ((bool)(this["SettingCheckBox_четверг_2пара"]));
            }
            set {
                this["SettingCheckBox_четверг_2пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBox_четверг_3пара {
            get {
                return ((bool)(this["SettingCheckBox_четверг_3пара"]));
            }
            set {
                this["SettingCheckBox_четверг_3пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBox_четверг_4пара {
            get {
                return ((bool)(this["SettingCheckBox_четверг_4пара"]));
            }
            set {
                this["SettingCheckBox_четверг_4пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBox_четверг_5пара {
            get {
                return ((bool)(this["SettingCheckBox_четверг_5пара"]));
            }
            set {
                this["SettingCheckBox_четверг_5пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBox_четверг_6пара {
            get {
                return ((bool)(this["SettingCheckBox_четверг_6пара"]));
            }
            set {
                this["SettingCheckBox_четверг_6пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBox_пятница_1пара {
            get {
                return ((bool)(this["SettingCheckBox_пятница_1пара"]));
            }
            set {
                this["SettingCheckBox_пятница_1пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBox_пятница_2пара {
            get {
                return ((bool)(this["SettingCheckBox_пятница_2пара"]));
            }
            set {
                this["SettingCheckBox_пятница_2пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBox_пятница_3пара {
            get {
                return ((bool)(this["SettingCheckBox_пятница_3пара"]));
            }
            set {
                this["SettingCheckBox_пятница_3пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBox_пятница_4пара {
            get {
                return ((bool)(this["SettingCheckBox_пятница_4пара"]));
            }
            set {
                this["SettingCheckBox_пятница_4пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBox_пятница_5пара {
            get {
                return ((bool)(this["SettingCheckBox_пятница_5пара"]));
            }
            set {
                this["SettingCheckBox_пятница_5пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBox_пятница_6пара {
            get {
                return ((bool)(this["SettingCheckBox_пятница_6пара"]));
            }
            set {
                this["SettingCheckBox_пятница_6пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBox_суббота_1пара {
            get {
                return ((bool)(this["SettingCheckBox_суббота_1пара"]));
            }
            set {
                this["SettingCheckBox_суббота_1пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBox_суббота_2пара {
            get {
                return ((bool)(this["SettingCheckBox_суббота_2пара"]));
            }
            set {
                this["SettingCheckBox_суббота_2пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBox_суббота_3пара {
            get {
                return ((bool)(this["SettingCheckBox_суббота_3пара"]));
            }
            set {
                this["SettingCheckBox_суббота_3пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBox_суббота_4пара {
            get {
                return ((bool)(this["SettingCheckBox_суббота_4пара"]));
            }
            set {
                this["SettingCheckBox_суббота_4пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBox_суббота_5пара {
            get {
                return ((bool)(this["SettingCheckBox_суббота_5пара"]));
            }
            set {
                this["SettingCheckBox_суббота_5пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBox_суббота_6пара {
            get {
                return ((bool)(this["SettingCheckBox_суббота_6пара"]));
            }
            set {
                this["SettingCheckBox_суббота_6пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBox_TopMost {
            get {
                return ((bool)(this["SettingCheckBox_TopMost"]));
            }
            set {
                this["SettingCheckBox_TopMost"] = value;
            }
        }
    }
}
