//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.1
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OIT_Call_Manager {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings_OneDay : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings_OneDay defaultInstance = ((Settings_OneDay)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings_OneDay())));
        
        public static Settings_OneDay Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingCheckBox_useOneDay {
            get {
                return ((bool)(this["SettingCheckBox_useOneDay"]));
            }
            set {
                this["SettingCheckBox_useOneDay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("03/24/2013 18:50:00")]
        public global::System.DateTime Setting_Date {
            get {
                return ((global::System.DateTime)(this["Setting_Date"]));
            }
            set {
                this["Setting_Date"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Setting_CheckBox_1пара {
            get {
                return ((bool)(this["Setting_CheckBox_1пара"]));
            }
            set {
                this["Setting_CheckBox_1пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Setting_CheckBox_2пара {
            get {
                return ((bool)(this["Setting_CheckBox_2пара"]));
            }
            set {
                this["Setting_CheckBox_2пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Setting_CheckBox_3пара {
            get {
                return ((bool)(this["Setting_CheckBox_3пара"]));
            }
            set {
                this["Setting_CheckBox_3пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Setting_CheckBox_4пара {
            get {
                return ((bool)(this["Setting_CheckBox_4пара"]));
            }
            set {
                this["Setting_CheckBox_4пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Setting_CheckBox_5пара {
            get {
                return ((bool)(this["Setting_CheckBox_5пара"]));
            }
            set {
                this["Setting_CheckBox_5пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Setting_CheckBox_6пара {
            get {
                return ((bool)(this["Setting_CheckBox_6пара"]));
            }
            set {
                this["Setting_CheckBox_6пара"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_Time_1пара_начало {
            get {
                return ((string)(this["Setting_Time_1пара_начало"]));
            }
            set {
                this["Setting_Time_1пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_Time_1пара_конец {
            get {
                return ((string)(this["Setting_Time_1пара_конец"]));
            }
            set {
                this["Setting_Time_1пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_Time_2пара_начало {
            get {
                return ((string)(this["Setting_Time_2пара_начало"]));
            }
            set {
                this["Setting_Time_2пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_Time_2пара_конец {
            get {
                return ((string)(this["Setting_Time_2пара_конец"]));
            }
            set {
                this["Setting_Time_2пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_Time_3пара_начало {
            get {
                return ((string)(this["Setting_Time_3пара_начало"]));
            }
            set {
                this["Setting_Time_3пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_Time_3пара_конец {
            get {
                return ((string)(this["Setting_Time_3пара_конец"]));
            }
            set {
                this["Setting_Time_3пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_Time_4пара_начало {
            get {
                return ((string)(this["Setting_Time_4пара_начало"]));
            }
            set {
                this["Setting_Time_4пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_Time_4пара_конец {
            get {
                return ((string)(this["Setting_Time_4пара_конец"]));
            }
            set {
                this["Setting_Time_4пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_Time_5пара_начало {
            get {
                return ((string)(this["Setting_Time_5пара_начало"]));
            }
            set {
                this["Setting_Time_5пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_Time_5пара_конец {
            get {
                return ((string)(this["Setting_Time_5пара_конец"]));
            }
            set {
                this["Setting_Time_5пара_конец"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_Time_6пара_начало {
            get {
                return ((string)(this["Setting_Time_6пара_начало"]));
            }
            set {
                this["Setting_Time_6пара_начало"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting_Time_6пара_конец {
            get {
                return ((string)(this["Setting_Time_6пара_конец"]));
            }
            set {
                this["Setting_Time_6пара_конец"] = value;
            }
        }
    }
}
